In [107]:
import pandas as pd
import numpy as np

In [108]:
#download the class movie reviews from here:
#https://docs.google.com/spreadsheets/d/17rCJzmWxqvAu9rkpkgt4ToccIlY4A1Ffuu1W9X3B8Ag/
#then read that in as a pandas dataframe

In [109]:
M = pd.read_csv("Movie Reviews - Sheet1.csv", index_col='Name')

In [110]:
def pearson(s1, s2):
    """Take two pd.Series objects and return a pearson correlation."""
    s1_c = s1 - s1.mean()
    s2_c = s2 - s2.mean()
    return np.sum(s1_c * s2_c) / np.sqrt(np.sum(s1_c ** 2) * np.sum(s2_c ** 2))

In [111]:
def get_recs(movie_name, M, num):

    import numpy as np
    reviews = []
    for title in M.columns:
        if title == movie_name:
            continue
        cor = pearson(M[movie_name], M[title])
        if np.isnan(cor):
            continue
        else:
            reviews.append((title, cor))
    
    reviews.sort(key=lambda tup: tup[1], reverse=True)
    return reviews[:num]

###Question 1:  What movie is most Similar to 'The fault in our stars' (60 pts)

In [112]:
recs = get_recs('The Fault in Our Stars', M, 1)

In [113]:
recs[:1]

[('Malificent', 0.39873118100855826)]

###Question 2:  Which movie(s) would you most like to see, based on your classmates experience? (40 pts)

In [114]:
#HINTS...

#the movies I've seen
my_ratings = M.ix['surya chandra reddy kovvuri'].dropna()
#the movie I've rated the highest
my_ratings.sort(ascending=False)
#the name of the movie I've rated the highest
fav_movie = my_ratings.index[0]

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:6: FutureWarning: sort is deprecated, use sort_values(inplace=True) for for INPLACE sorting

In [115]:
#Ratings given by me
my_ratings

The Hobbit                               5
Divergent                                4
Interstellar                             4
Transformers                             4
Guardians of the Galaxy                  4
The Hunger Games: Mockingjay - Part 1    4
The Lego Movie                           3
Malificent                               2
Name: surya chandra reddy kovvuri, dtype: float64

In [116]:
#favourite movie
fav_movie

'The Hobbit'

In [117]:
recs = get_recs(fav_movie, M, 10)
recs

[('Transformers', 0.23158589781904093),
 ('How to Train your Dragon 2', 0.20409308725855824),
 ('The Hunger Games: Mockingjay - Part 1', 0.1881325539168438),
 ('Divergent', 0.15997456087528947),
 ('Malificent', 0.10707758674614519),
 ('Guardians of the Galaxy', 0.091970088979922718),
 ('Interstellar', 0.080389918244681807),
 ('Godzilla', 0.07937889482608522),
 ('300: Rise of an Empire', 0.063533970228666581),
 ('Big Hero 6', 0.054661249145810886)]

In [100]:
#based on my classmates experience, the movie I'd like to see is "transformers".

###Question 3: Bonus Question...  For all the movies you haven't seen, can you predict how you'd rate them using your the class reviews? (10 pts)

In [101]:
notviewed = M.ix['surya chandra reddy kovvuri']
notviewed.sort()
for i in range(0, notviewed.count(), 1):
    notviewed.drop(notviewed.index[0], inplace=True)

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort is deprecated, use sort_values(inplace=True) for for INPLACE sorting
  from ipykernel import kernelapp as app

In [102]:
notviewed

American Sniper              NaN
Big Hero 6                   NaN
Godzilla                     NaN
How to Train your Dragon 2   NaN
Gone Girl                    NaN
The Fault in Our Stars       NaN
Unbroken                     NaN
300: Rise of an Empire       NaN
Name: surya chandra reddy kovvuri, dtype: float64

In [103]:
M

,American Sniper,The Hunger Games: Mockingjay - Part 1,Guardians of the Galaxy,The Lego Movie,The Hobbit,Transformers,Malificent,Big Hero 6,Godzilla,Interstellar,How to Train your Dragon 2,Gone Girl,Divergent,The Fault in Our Stars,Unbroken,300: Rise of an Empire
Name,,,,,,,,,,,,,,,,
Aarti Jaiswal,4.000000,NaN,NaN,NaN,4,3,NaN,5,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN
Aditya Dharmasagar,5.000000,NaN,NaN,4,5,4,4,NaN,4,5,5,5,4,4,NaN,5
Adrian Cavallaris,NaN,4,3,NaN,4,2,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN
Ahmed Muheebuddin,5.000000,NaN,4,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aishwarya reddy,NaN,3,4,3,4,4,3,NaN,4,4,3,5,NaN,4,NaN,3
Akhilesh,NaN,NaN,4,3,5,4,NaN,NaN,NaN,5,NaN,3,NaN,NaN,NaN,5
Andrew Webb,4.000000,3,4,3,3,2,NaN,4,3,4,3,4,2,3,NaN,3
Anirudh,3.000000,4,5,3,5,3,5,NaN,4,NaN,NaN,2,3,4,NaN,2
Anirudh Thota,NaN,3,4,3,3,4,NaN,NaN,3,4,3,NaN,NaN,NaN,NaN,4
anurag,4.000000,NaN,NaN,NaN,3,NaN,NaN,NaN,5,NaN,3,NaN,3,NaN,NaN,5
Anusha Putta,NaN,NaN,NaN,NaN,4,4,NaN,NaN,3,NaN,NaN,5,4,NaN,NaN,NaN
Arun Vedere,4.000000,3,4,3,5,5,3,NaN,3,5,4,NaN,NaN,NaN,NaN,1
Ashutosh Sureka,5.000000,4,5,5,5,5,0,5,2,3,5,3,3,2,2,4
Aswini kumar,4.000000,4,5,NaN,NaN,NaN,NaN,5,3,5,4,NaN,NaN,NaN,NaN,4
azam,4.000000,NaN,3,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Benjamin Baysinger,5.000000,4,5,5,3,2,2,4,4,4,4,5,1,4,3,2
Bhuvana Posina,5.000000,4,4,5,3,5,3,3,4,5,3,5,3,3,3,5
Bradley Brubaker,NaN,1,5,5,5,4,NaN,NaN,4,NaN,4,NaN,3,NaN,NaN,2
Brant Mullinix,NaN,4,4,4,5,3,NaN,NaN,NaN,5,3,3,NaN,NaN,NaN,4
Charlie,NaN,2,3,NaN,3,2,3,NaN,4,5,2,NaN,2,3,NaN,2
David Huang,5.000000,NaN,4,NaN,NaN,5,NaN,NaN,4,5,NaN,NaN,NaN,NaN,NaN,5
David Reyling,NaN,1,NaN,NaN,1,1,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Evan Piercy,4.000000,NaN,NaN,4,NaN,4,NaN,NaN,NaN,5,NaN,2,NaN,NaN,NaN,2
Graham Bullard,3.000000,2,4,3,4,NaN,3,4,3,4,NaN,4,NaN,NaN,4,3
Greg Werner,5.000000,3,3,NaN,NaN,4,4,NaN,NaN,5,4,5,4,NaN,NaN,4
Harish Kallianpur,5.000000,3,NaN,NaN,5,4,4,NaN,4,5,4,NaN,3,NaN,NaN,3
Heather Sanders,NaN,3,NaN,1,3,3,3,4,NaN,NaN,3,NaN,3,3,5,NaN
HJ SONG,NaN,2,3,4,4,5,NaN,4,4,5,5,NaN,NaN,NaN,5,5
J A Barnes,NaN,3,4,NaN,4,4,NaN,NaN,NaN,NaN,3,NaN,3,NaN,NaN,NaN
Jake Metzger,NaN,NaN,4,NaN,NaN,2,3,NaN,2,NaN,NaN,5,NaN,NaN,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sai bhargav musuluri,3.000000,NaN,5,NaN,4,NaN,NaN,5,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN
Sai Sampath,NaN,3,4,3,4,4,3,NaN,4,4,3,5,NaN,4,NaN,3
Sai Yallapragada,5.000000,2,2,3,NaN,3,NaN,NaN,1,5,NaN,NaN,2,NaN,NaN,4
saikiran reddy,3.000000,4,4,NaN,4,5,4,NaN,5,5,4,4,2,5,NaN,2
sandeep katragadda,5.000000,NaN,4,NaN,4,NaN,4,NaN,NaN,4,5,4,NaN,NaN,NaN,NaN
Sara Collins,NaN,5,5,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN
Shannon Morrison,NaN,3,4,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN
Shiva rama raju Chekuri,4.000000,4,4,3,4,5,4,NaN,4,5,4,5,NaN,NaN,NaN,4
siddanth sudarshan,5.000000,3,3,NaN,2,NaN,NaN,NaN,NaN,4,NaN,4,NaN,NaN,NaN,5
Sina Tuy,NaN,3,4,3,5,2,3,4,3,NaN,3,4,3,2,NaN,2
solomon choppara,5.000000,4,4,3,5,5,4,NaN,4,5,2,4,3,3,NaN,5
Sundar Prasad,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,4
Sunil Nandikanti,NaN,NaN,3,3,NaN,5,NaN,NaN,4,5,5,NaN,NaN,4,NaN,4
surya chandra reddy kovvuri,NaN,4,4,3,5,4,2,NaN,NaN,4,NaN,NaN,4,NaN,NaN,NaN
Susan Huang,NaN,NaN,NaN,3,4,2,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Suyendra,NaN,3,4,3,5,2,3,3,3,NaN,5,NaN,3,4,2,5
Syed Abbas Hussaini,4.000000,4,NaN,4,NaN,5,NaN,NaN,4,5,5,4,NaN,4,NaN,3
Syed Farzan,NaN,3,NaN,NaN,4,3,NaN,NaN,3,4,3,NaN,NaN,NaN,NaN,3
Thomas Podlipni,5.000000,3,5,4,4,1,NaN,NaN,NaN,NaN,4,NaN,3,NaN,NaN,4
Trudy Kline,3.000000,5,5,3,3,4,NaN,NaN,2,NaN,NaN,2,4,NaN,NaN,1
Tyler Vitanova,NaN,NaN,4,4,4,2,4,3,2,4,2,3,3,NaN,NaN,NaN
ugesh reddy challa,NaN,3,2,1,NaN,NaN,3,NaN,NaN,5,NaN,NaN,3,3,NaN,5
veerendra battula,3.000000,NaN,2,1,NaN,2,3,NaN,2,NaN,1,3,2,NaN,NaN,5
Venkatesh Komma,NaN,NaN,4,NaN,5,NaN,4,3,4,5,4,4,5,5,4,5
Violeta Lee Fay,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,5,NaN,3,NaN,NaN,NaN,NaN,2
Yinka Adeyemo,4.000000,NaN,4,NaN,4,NaN,NaN,4,NaN,NaN,4,NaN,NaN,NaN,NaN,4
Sai Sharan Vellala,5.000000,4,3,2,5,5,4,5,5,5,3,2,NaN,3,2,5
NaN,159.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,4.184211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
print "Pearson Correlation coefficient of :"
a= []
for i in range(0, M.shape[0], 1): 
    cor=pearson(M.ix[59], M.ix[i])
    print "(" + M.index[59] + " , " + str(M.index[i]) + ") :", cor
    a.append(cor)

Pearson Correlation coefficient of :
(surya chandra reddy kovvuri , Aarti Jaiswal) : -0.0753778361444
(surya chandra reddy kovvuri , Aditya Dharmasagar) : 0.430820218428
(surya chandra reddy kovvuri , Adrian Cavallaris) : 0.143019388387
(surya chandra reddy kovvuri , Ahmed Muheebuddin) : -0.376889180722
(surya chandra reddy kovvuri , Aishwarya reddy) : 0.427668601724
(surya chandra reddy kovvuri , Akhilesh) : 0.400772744797
(surya chandra reddy kovvuri , Andrew Webb) : -0.063418933962
(surya chandra reddy kovvuri , Anirudh) : -0.0123586830973
(surya chandra reddy kovvuri , Anirudh Thota) : 0.0238365647311
(surya chandra reddy kovvuri , anurag) : -0.242440568938
(surya chandra reddy kovvuri , Anusha Putta) : 0.0
(surya chandra reddy kovvuri , Arun Vedere) : 0.437049650148
(surya chandra reddy kovvuri , Ashutosh Sureka) : 0.534862186741
(surya chandra reddy kovvuri , Aswini kumar) : 0.0712253602873
(surya chandra reddy kovvuri , azam) : 0.301511344578
(surya chandra reddy kovvuri , Benjamin Baysinger) : 0.0435761908089
(surya chandra reddy kovvuri , Bhuvana Posina) : 0.0
(surya chandra reddy kovvuri , Bradley Brubaker) : 0.0266500895445
(surya chandra reddy kovvuri , Brant Mullinix) : 0.273200347277
(surya chandra reddy kovvuri , Charlie) : -0.0156091549942
(surya chandra reddy kovvuri , David Huang) : -8.19954044524e-17
(surya chandra reddy kovvuri , David Reyling) : -0.215410109214
(surya chandra reddy kovvuri , Evan Piercy) : 0.019462473604
(surya chandra reddy kovvuri , Graham Bullard) : 0.328515516813
(surya chandra reddy kovvuri , Greg Werner) : -0.0385257064265
(surya chandra reddy kovvuri , Harish Kallianpur) : 0.174077655956
(surya chandra reddy kovvuri , Heather Sanders) : 0.221541631723
(surya chandra reddy kovvuri , HJ SONG) : -0.0718021129732
(surya chandra reddy kovvuri , J A Barnes) : 0.217597069945
(surya chandra reddy kovvuri , Jake Metzger) : 0.0339829529892
(surya chandra reddy kovvuri , James Goodpasture) : 0.287853866545
(surya chandra reddy kovvuri , Jared Knowles) : 0.447636892893
(surya chandra reddy kovvuri , Jessica Fong) : 4.32153726227e-17
(surya chandra reddy kovvuri , Jonathan Doll) : 0.267564775505
(surya chandra reddy kovvuri , Josna Rajan) : -0.24425210523
(surya chandra reddy kovvuri , krishna sai) : -0.0535686955444
(surya chandra reddy kovvuri , M A Nissar) : -0.134839972493
(surya chandra reddy kovvuri , Maheshwar Reddy) : 0.169600131325
(surya chandra reddy kovvuri , Manideep Maddipatla) : 0.316197881051
(surya chandra reddy kovvuri , Michael Cooper) : 0.0
(surya chandra reddy kovvuri , Mike) : 0.327231446503
(surya chandra reddy kovvuri , Olumuyiwa Durojaiye) : 0.0562321557116
(surya chandra reddy kovvuri , Onsiri Tapsarn) : nan
(surya chandra reddy kovvuri , Pavithra Shetty) : -0.112494260643
(surya chandra reddy kovvuri , Rajesh Kinkirla) : 0.366613685513
(surya chandra reddy kovvuri , Ryan Hansen) : 0.382518426119
(surya chandra reddy kovvuri , sai bhargav musuluri) : -0.0476731294623
(surya chandra reddy kovvuri , Sai Sampath) : 0.427668601724
(surya chandra reddy kovvuri , Sai Yallapragada) : -0.0266500895445
(surya chandra reddy kovvuri , saikiran reddy) : 0.00684311126814
(surya chandra reddy kovvuri , sandeep katragadda) : 0.0
(surya chandra reddy kovvuri , Sara Collins) : 0.696310623823
(surya chandra reddy kovvuri , Shannon Morrison) : 0.153864363724
(surya chandra reddy kovvuri , Shiva rama raju Chekuri) : 0.287629477372
(surya chandra reddy kovvuri , siddanth sudarshan) : -0.379941632828
(surya chandra reddy kovvuri , Sina Tuy) : 0.347676747683
(surya chandra reddy kovvuri , solomon choppara) : 0.276955854703
(surya chandra reddy kovvuri , Sundar Prasad) : 0.0870388279778
(surya chandra reddy kovvuri , Sunil Nandikanti) : 0.193121819834
(surya chandra reddy kovvuri , surya chandra reddy kovvuri) : 1.0
(surya chandra reddy kovvuri , Susan Huang) : 0.208917912623
(surya chandra reddy kovvuri , Suyendra) : 0.306592603028
(surya chandra reddy kovvuri , Syed Abbas Hussaini) : 0.112366643744
(surya chandra reddy kovvuri , Syed Farzan) : 0.331270674434
(surya chandra reddy kovvuri , Thomas Podlipni) : -0.0615457454897
(surya chandra reddy kovvuri , Trudy Kline) : 0.129550055126
(surya chandra reddy kovvuri , Tyler Vitanova) : -0.147289561327
(surya chandra reddy kovvuri , ugesh reddy challa) : 0.230243165521
(surya chandra reddy kovvuri , veerendra battula) : -0.0363269609772
(surya chandra reddy kovvuri , Venkatesh Komma) : 0.32897584748
(surya chandra reddy kovvuri , Violeta Lee Fay) : 0.0512881212414
(surya chandra reddy kovvuri , Yinka Adeyemo) : nan
(surya chandra reddy kovvuri , Sai Sharan Vellala) : 0.271346507827
(surya chandra reddy kovvuri , nan) : nan
(surya chandra reddy kovvuri , nan) : nan
(surya chandra reddy kovvuri , nan) : nan

In [105]:
def pred_rate(d, a):
    j=0
    k=0
    for i in range(0, d.shape[0], 1):
        if d.irow(i)>0 and a[i]>0: 
            j= j+(a[i]*d.irow(i))
            k= k+a[i]
        else:
            continue
    return j/k

In [106]:
print "Ratings for movies I've not watched and according to classmates"
for i in range(0, notviewed.shape[0], 1):  
    d=M[notviewed.index[i]]
    rate=pred_rate(d, a)
    print notviewed.index[i] +": ", rate.round(1)

Ratings for movies I've not watched and according to classmates
American Sniper:  4.3
Big Hero 6:  4.1
Godzilla:  3.5
How to Train your Dragon 2:  3.8
Gone Girl:  3.9
The Fault in Our Stars:  3.5
Unbroken:  3.5
300: Rise of an Empire:  3.7

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:5: FutureWarning: irow(i) is deprecated. Please use .iloc[i] or .iat[i]
C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:6: FutureWarning: irow(i) is deprecated. Please use .iloc[i] or .iat[i]